### ISSUE TITLE
Change HomePage Layout

### ISSUE THREAD

**Issue by danleyb2** [danleyb2/danleyb2.github.io#17]
Copy the layout from https://danleyb2.dev/projects as the new homepage at https://danleyb2.dev/
```txt
Add a centered rounded image on top of "Projects" for a self potrait
Replace "Projects" with "Nyaundi Brian"

Replace the text under it with a short intro:
===
Hello, I'm Nyaundi Brian, a Full-Stack developer and electronics enthusiast.
I am currently at Platerecognizer(https://platerecognizer.com/) building Vision AI models and creating integrations around them such as APIs, sites and scripts.

I was previously an Implementations Lead at InterIntel Technologies across their various products such as Nenasasa (a Bulk SMS Platform) and Mipay (a Payment Gateway).
```
### TODOs on Start Page

- [x] Just remove the image entirely and move it to about page
- [x] Make the text under the name shorter "I'm Nyaundi Brian, a Full-Stack developer and electronics enthusiast."
- [x] Move the rest of the text to under the image in the About page
- [x] Just remove the social media icons because they exist at the bottom of the page
- [x] Create below 2 sections on the main page. Use similar layout to Projects page "Backend", "Frontend" and "Mobile"

1. "Latest Posts"
2. "Projects and Experience" 

For the section "Latest Posts"
- replace the text below it with: "Recent Posts from my blog"
- Display recent blog posts. Check #16 
- add a link below the 3 columns with text "More" that goes to https://danleyb2.dev/blog

For the section "Projects and Experience"

- replace the text below it with: "My key projects and achievements from work, freelancing and open source contributions"
- add a link "See all projects" below the 3 columns that goes to https://danleyb2.dev/projects
- add another link "CV" below the 3 columns that goes to https://www.linkedin.com/in/danleyb2/
